# make sure this file is in gitignore!

spring:
  'config.activate.on-profile': dev

  # make sure to create metadata 
  datasource:
    student:
      driver-class-name: org.mariadb.jdbc.Driver
      # if you have multiple datasources --> instead of url --> jdbc-url
      jdbc-url: jdbc:mariadb://localhost:3306/demo
      username: root
      password: sookim482.dev
    teacher:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/demo_teacher
      username: root
      password: sookim482.dev
